version: '3.3'

services:
  app:
    image: python:3.11.2
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: uvicorn crm_backend:app --workers 3 --host ${APP_HOST} --port ${APP_PORT}
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
    ports:
      - ${APP_PORT}:${APP_PORT}

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432